import { CaseTypeConfig, PlatformConfig } from '../types';

export const DEFAULT_PLATFORMS: PlatformConfig[] = [
  { id: 'facebook', name: 'Facebook', nameAr: 'فيسبوك', icon: 'Facebook', isActive: true, sortOrder: 1, isPopular: true },
  { id: 'instagram', name: 'Instagram', nameAr: 'إنستغرام', icon: 'Instagram', isActive: true, sortOrder: 2, isPopular: true },
  { id: 'x', name: 'X', nameAr: 'إكس (تويتر)', icon: 'Twitter', isActive: true, sortOrder: 3, isPopular: true },
  { id: 'youtube', name: 'YouTube', nameAr: 'يوتيوب', icon: 'Youtube', isActive: true, sortOrder: 4, isPopular: true },
  { id: 'tiktok', name: 'TikTok', nameAr: 'تيك توك', icon: 'Video', isActive: true, sortOrder: 5 },
  { id: 'telegram', name: 'Telegram', nameAr: 'تيليجرام', icon: 'Send', isActive: true, sortOrder: 6 },
  { id: 'whatsapp', name: 'WhatsApp', nameAr: 'واتساب', icon: 'MessageCircle', isActive: true, sortOrder: 7 },
  { id: 'linkedin', name: 'LinkedIn', nameAr: 'لينكد إن', icon: 'Linkedin', isActive: true, sortOrder: 8 },
  { id: 'snapchat', name: 'Snapchat', nameAr: 'سناب شات', icon: 'Ghost', isActive: true, sortOrder: 9 },
  { id: 'reddit', name: 'Reddit', nameAr: 'ريديت', icon: 'Globe', isActive: true, sortOrder: 10 },
  { id: 'google', name: 'Google', nameAr: 'جوجل', icon: 'Search', isActive: true, sortOrder: 11 },
  { id: 'discord', name: 'Discord', nameAr: 'ديسكورد', icon: 'MessageSquare', isActive: true, sortOrder: 12 },
  { id: 'other', name: 'Other', nameAr: 'أخرى', icon: 'HelpCircle', isActive: true, sortOrder: 13 },
];

export const DEFAULT_CASE_TYPES: CaseTypeConfig[] = [
  {
    id: 'impersonation',
    key: 'impersonation',
    labelAr: 'حساب منتحل',
    labelEn: 'Impersonation Account',
    icon: 'UserX',
    isActive: true,
    sortOrder: 1,
    isSystem: true,
    fields: [
      { key: 'platform', labelAr: 'المنصة', labelEn: 'Platform', type: 'select' },
      { key: 'originalAccountUrl', labelAr: 'رابط الحساب الأصلي', labelEn: 'Original Account URL', type: 'url', placeholderAr: 'https://...', placeholderEn: 'https://...' },
      { key: 'impersonatingAccountUrl', labelAr: 'رابط الحساب المنتحل', labelEn: 'Impersonating Account URL', type: 'url', placeholderAr: 'https://...', placeholderEn: 'https://...' },
      { key: 'username', labelAr: 'اسم المستخدم (Username)', labelEn: 'Username', type: 'text', placeholderAr: '@username', placeholderEn: '@username' },
      { key: 'accountName', labelAr: 'اسم الحساب الظاهر', labelEn: 'Account Name', type: 'text' },
      { key: 'postUrl', labelAr: 'رابط المنشور', labelEn: 'Post URL', type: 'url' },
      { key: 'pageUrl', labelAr: 'رابط الصفحة', labelEn: 'Page URL', type: 'url' },
      { key: 'notes', labelAr: 'ملاحظات إضافية', labelEn: 'Notes', type: 'textarea' },
    ]
  },
  {
    id: 'content_removal',
    key: 'content_removal',
    labelAr: 'حذف منشور / محتوى',
    labelEn: 'Content Removal',
    icon: 'Trash2',
    isActive: true,
    sortOrder: 2,
    isSystem: true,
    fields: [
      { key: 'platform', labelAr: 'المنصة', labelEn: 'Platform', type: 'select' },
      { key: 'postUrl', labelAr: 'رابط المنشور / المحتوى', labelEn: 'Post URL', type: 'url' },
      { key: 'accountUrl', labelAr: 'رابط حساب الناشر', labelEn: 'Publisher Account URL', type: 'url' },
      { key: 'contentType', labelAr: 'نوع المحتوى', labelEn: 'Content Type', type: 'text', placeholderAr: 'فيديو، صورة، منشور، تعليق', placeholderEn: 'Video, Image, Post, Comment' },
      { key: 'reason', labelAr: 'سبب الحذف / المخالفة', labelEn: 'Reason for Removal', type: 'text' },
      { key: 'removalDate', labelAr: 'تاريخ طلب الإزالة', labelEn: 'Removal Date', type: 'date' },
      { key: 'description', labelAr: 'وصف المخالفة', labelEn: 'Description', type: 'textarea' },
      { key: 'notes', labelAr: 'ملاحظات', labelEn: 'Notes', type: 'textarea' },
    ]
  },
  {
    id: 'infosec',
    key: 'infosec',
    labelAr: 'أمن معلومات',
    labelEn: 'Information Security',
    icon: 'ShieldAlert',
    isActive: true,
    sortOrder: 3,
    isSystem: true,
    fields: [
      { key: 'issueType', labelAr: 'نوع المشكلة الأمنية', labelEn: 'Issue Type', type: 'text', placeholderAr: 'تسريب، ثغرة، هجوم، وصول غير مصرح', placeholderEn: 'Leak, Vulnerability, Attack, Breach' },
      { key: 'system', labelAr: 'النظام المتأثر', labelEn: 'Affected System', type: 'text' },
      { key: 'domain', labelAr: 'النطاق (Domain)', labelEn: 'Domain', type: 'text' },
      { key: 'ip', labelAr: 'عنوان IP', labelEn: 'IP Address', type: 'text' },
      { key: 'affectedAsset', labelAr: 'الأصل المتأثر', labelEn: 'Affected Asset', type: 'text' },
      { key: 'severity', labelAr: 'مستوى الخطورة', labelEn: 'Severity', type: 'select', options: [
        { value: 'critical', labelAr: 'حرج جداً', labelEn: 'Critical' },
        { value: 'high', labelAr: 'عالي', labelEn: 'High' },
        { value: 'medium', labelAr: 'متوسط', labelEn: 'Medium' },
        { value: 'low', labelAr: 'منخفض', labelEn: 'Low' },
      ]},
      { key: 'description', labelAr: 'التفاصيل التقنية', labelEn: 'Technical Details', type: 'textarea' },
      { key: 'notes', labelAr: 'ملاحظات وتوصيات', labelEn: 'Notes & Recommendations', type: 'textarea' },
    ]
  },
  {
    id: 'extortion',
    key: 'extortion',
    labelAr: 'قضية ابتزاز',
    labelEn: 'Extortion Case',
    icon: 'AlertTriangle',
    isActive: true,
    sortOrder: 4,
    isSystem: true,
    fields: [
      { key: 'platform', labelAr: 'المنصة المستخدمة للابتزاز', labelEn: 'Platform', type: 'select' },
      { key: 'account', labelAr: 'اسم / رقم حساب المبتز', labelEn: 'Extortionist Account/Number', type: 'text' },
      { key: 'accountUrl', labelAr: 'رابط حساب المبتز', labelEn: 'Extortionist Account URL', type: 'url' },
      { key: 'contactMethod', labelAr: 'طريقة التواصل / التهديد', labelEn: 'Contact Method', type: 'text' },
      { key: 'contentType', labelAr: 'نوع المحتوى المبتز به', labelEn: 'Extortion Material Type', type: 'text' },
      { key: 'incidentDate', labelAr: 'تاريخ بدء الواقعة', labelEn: 'Incident Date', type: 'date' },
      { key: 'description', labelAr: 'وصف الواقعة وتفاصيل التهديد', labelEn: 'Incident Description', type: 'textarea' },
      { key: 'notes', labelAr: 'ملاحظات وإجراءات الحماية', labelEn: 'Protection Notes', type: 'textarea' },
    ]
  },
  {
    id: 'penetration_testing',
    key: 'penetration_testing',
    labelAr: 'طلب اختبار اختراق',
    labelEn: 'Penetration Testing Request',
    icon: 'Terminal',
    isActive: true,
    sortOrder: 5,
    isSystem: true,
    fields: [
      { key: 'company', labelAr: 'الشركة / الجهة', labelEn: 'Company / Organization', type: 'text' },
      { key: 'domain', labelAr: 'النطاق المستهدف', labelEn: 'Target Domain', type: 'text' },
      { key: 'ip', labelAr: 'عناوين IP / النطاق', labelEn: 'IP / Range', type: 'text' },
      { key: 'target', labelAr: 'الهدف الرئيسي', labelEn: 'Main Target', type: 'text' },
      { key: 'testType', labelAr: 'نوع الاختبار', labelEn: 'Test Type', type: 'select', options: [
        { value: 'web', labelAr: 'تطبيق ويب (Web Application)', labelEn: 'Web Application' },
        { value: 'mobile', labelAr: 'تطبيق هاتف (Mobile Application)', labelEn: 'Mobile Application' },
        { value: 'api', labelAr: 'واجهة برمجة (API)', labelEn: 'API' },
        { value: 'network', labelAr: 'شبكة داخلية/خارجية (Network)', labelEn: 'Network' },
        { value: 'infra', labelAr: 'بنية تحتية وسحابية (Infrastructure)', labelEn: 'Infrastructure' },
        { value: 'other', labelAr: 'أخرى', labelEn: 'Other' },
      ]},
      { key: 'scope', labelAr: 'نطاق العمل (Scope)', labelEn: 'Scope', type: 'text' },
      { key: 'environment', labelAr: 'بيئة الفحص (Production / Staging)', labelEn: 'Environment', type: 'text' },
      { key: 'description', labelAr: 'متطلبات إضافية', labelEn: 'Requirements', type: 'textarea' },
      { key: 'notes', labelAr: 'ملاحظات', labelEn: 'Notes', type: 'textarea' },
    ]
  },
  {
    id: 'account_recovery',
    key: 'account_recovery',
    labelAr: 'استعادة حساب',
    labelEn: 'Account Recovery',
    icon: 'KeyRound',
    isActive: true,
    sortOrder: 6,
    isSystem: true,
    fields: [
      { key: 'platform', labelAr: 'المنصة', labelEn: 'Platform', type: 'select' },
      { key: 'accountUrl', labelAr: 'رابط الحساب المراد استعادته', labelEn: 'Account URL', type: 'url' },
      { key: 'username', labelAr: 'اسم المستخدم', labelEn: 'Username', type: 'text' },
      { key: 'originalEmail', labelAr: 'البريد الإلكتروني الأصلي', labelEn: 'Original Email', type: 'text' },
      { key: 'originalPhone', labelAr: 'رقم الهاتف الأصلي', labelEn: 'Original Phone', type: 'text' },
      { key: 'lossDate', labelAr: 'تاريخ فقدان الوصول', labelEn: 'Loss Date', type: 'date' },
      { key: 'notes', labelAr: 'ملاحظات وتفاصيل إضافية', labelEn: 'Notes', type: 'textarea' },
    ]
  },
  {
    id: 'account_hacking',
    key: 'account_hacking',
    labelAr: 'اختراق حساب',
    labelEn: 'Account Hacking',
    icon: 'Lock',
    isActive: true,
    sortOrder: 7,
    isSystem: true,
    fields: [
      { key: 'platform', labelAr: 'المنصة', labelEn: 'Platform', type: 'select' },
      { key: 'accountUrl', labelAr: 'رابط الحساب المخترق', labelEn: 'Hacked Account URL', type: 'url' },
      { key: 'hackerEmail', labelAr: 'بريد المخترق (إن وجد)', labelEn: 'Hacker Email (if known)', type: 'text' },
      { key: 'twoFaStatus', labelAr: 'حالة التحقق بخطوتين', labelEn: '2FA Status', type: 'text' },
      { key: 'notes', labelAr: 'ملاحظات', labelEn: 'Notes', type: 'textarea' },
    ]
  },
  {
    id: 'identity_impersonation',
    key: 'identity_impersonation',
    labelAr: 'انتحال شخصية',
    labelEn: 'Identity Impersonation',
    icon: 'Users',
    isActive: true,
    sortOrder: 8,
    isSystem: true,
    fields: [
      { key: 'victimName', labelAr: 'اسم الشخص المنتحَل', labelEn: 'Victim Name', type: 'text' },
      { key: 'platform', labelAr: 'المنصة', labelEn: 'Platform', type: 'select' },
      { key: 'impersonatorUrl', labelAr: 'رابط الحساب المنتحل', labelEn: 'Impersonator URL', type: 'url' },
      { key: 'officialDocAvailable', labelAr: 'هل الوثائق الرسمية متوفرة؟', labelEn: 'Official ID Available?', type: 'text' },
      { key: 'notes', labelAr: 'ملاحظات', labelEn: 'Notes', type: 'textarea' },
    ]
  },
  {
    id: 'intellectual_property',
    key: 'intellectual_property',
    labelAr: 'حقوق ملكية فكرية',
    labelEn: 'Intellectual Property',
    icon: 'Copyright',
    isActive: true,
    sortOrder: 9,
    isSystem: true,
    fields: [
      { key: 'platform', labelAr: 'المنصة', labelEn: 'Platform', type: 'select' },
      { key: 'workTitle', labelAr: 'اسم العمل / العلامة التجارية', labelEn: 'Work / Trademark Title', type: 'text' },
      { key: 'infringingUrl', labelAr: 'رابط المحتوى المنتهك', labelEn: 'Infringing URL', type: 'url' },
      { key: 'originalWorkUrl', labelAr: 'رابط العمل الأصلي أو التسجيل', labelEn: 'Original Proof URL', type: 'url' },
      { key: 'notes', labelAr: 'ملاحظات', labelEn: 'Notes', type: 'textarea' },
    ]
  },
  {
    id: 'platform_report',
    key: 'platform_report',
    labelAr: 'بلاغ منصة',
    labelEn: 'Platform Report',
    icon: 'Flag',
    isActive: true,
    sortOrder: 10,
    isSystem: true,
    fields: [
      { key: 'platform', labelAr: 'المنصة', labelEn: 'Platform', type: 'select' },
      { key: 'reportRefNumber', labelAr: 'رقم مرجع البلاغ لدى المنصة', labelEn: 'Platform Case/Ref #', type: 'text' },
      { key: 'targetUrl', labelAr: 'الرابط المبلّغ عنه', labelEn: 'Reported URL', type: 'url' },
      { key: 'notes', labelAr: 'ملاحظات', labelEn: 'Notes', type: 'textarea' },
    ]
  },
  {
    id: 'security_consultation',
    key: 'security_consultation',
    labelAr: 'استشارة أمنية',
    labelEn: 'Security Consultation',
    icon: 'ShieldCheck',
    isActive: true,
    sortOrder: 11,
    isSystem: true,
    fields: [
      { key: 'topic', labelAr: 'موضوع الاستشارة', labelEn: 'Topic', type: 'text' },
      { key: 'clientEntity', labelAr: 'الجهة الطالبة', labelEn: 'Client / Entity', type: 'text' },
      { key: 'notes', labelAr: 'تفاصيل وملاحظات الاستشارة', labelEn: 'Details & Notes', type: 'textarea' },
    ]
  },
  {
    id: 'technical_issue',
    key: 'technical_issue',
    labelAr: 'مشكلة تقنية',
    labelEn: 'Technical Issue',
    icon: 'Wrench',
    isActive: true,
    sortOrder: 12,
    isSystem: true,
    fields: [
      { key: 'system', labelAr: 'النظام / الموقع المتأثر', labelEn: 'Affected System', type: 'text' },
      { key: 'errorDetails', labelAr: 'رسالة الخطأ أو تفاصيل العطل', labelEn: 'Error Details', type: 'textarea' },
      { key: 'notes', labelAr: 'ملاحظات', labelEn: 'Notes', type: 'textarea' },
    ]
  },
  {
    id: 'general_request',
    key: 'general_request',
    labelAr: 'طلب عام',
    labelEn: 'General Request',
    icon: 'FolderPlus',
    isActive: true,
    sortOrder: 13,
    isSystem: true,
    fields: [
      { key: 'subject', labelAr: 'الموضوع', labelEn: 'Subject', type: 'text' },
      { key: 'description', labelAr: 'التفاصيل', labelEn: 'Description', type: 'textarea' },
      { key: 'notes', labelAr: 'ملاحظات', labelEn: 'Notes', type: 'textarea' },
    ]
  },
  {
    id: 'other',
    key: 'other',
    labelAr: 'أخرى',
    labelEn: 'Other',
    icon: 'FileQuestion',
    isActive: true,
    sortOrder: 14,
    isSystem: true,
    fields: [
      { key: 'customCategory', labelAr: 'تصنيف مخصص', labelEn: 'Custom Category', type: 'text' },
      { key: 'description', labelAr: 'التفاصيل', labelEn: 'Description', type: 'textarea' },
      { key: 'notes', labelAr: 'ملاحظات', labelEn: 'Notes', type: 'textarea' },
    ]
  }
];
